"""Added materials tables

Revision ID: 4bfcac40e851
Revises: f7dcfea1b60c
Create Date: 2025-02-24 17:10:19.729380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfcac40e851'
down_revision: Union[str, None] = 'f7dcfea1b60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_type')
    )
    op.create_table('material_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_title', sa.String(length=255), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_title_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_title_id'], ['material_titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_title_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_title_id'], ['material_titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_user')
    op.drop_table('material_stock')
    op.drop_table('material_titles')
    op.drop_table('material_types')
    # ### end Alembic commands ###
