"""Add remedial_user_id to Application

Revision ID: ab3dd9366a97
Revises: a0a21070a04f
Create Date: 2025-02-07 15:45:35.895636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3dd9366a97'
down_revision: Union[str, None] = 'a0a21070a04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('remedial_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'users', ['remedial_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'remedial_user_id')
    # ### end Alembic commands ###
